-- Pillar 2: Ghost Churn Detection Monitor
-- Roster uploads, member diffing, switch alerts, and email forwarding config.

-- Storage bucket for raw roster files (idempotent)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'roster-uploads', 'roster-uploads', false, 10485760,
  ARRAY['text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel','application/octet-stream']::text[]
)
ON CONFLICT (id) DO NOTHING;

-- Brokers can upload roster files to their own agency folder
DROP POLICY IF EXISTS "roster_uploads_agency_write" ON storage.objects;
CREATE POLICY "roster_uploads_agency_write" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'roster-uploads'
    AND (storage.foldername(name))[1] IN (
      SELECT id::text FROM agencies WHERE owner_id = auth.uid()
      UNION
      SELECT agency_id::text FROM brokers WHERE user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "roster_uploads_agency_read" ON storage.objects;
CREATE POLICY "roster_uploads_agency_read" ON storage.objects
  FOR SELECT USING (
    bucket_id = 'roster-uploads'
    AND (storage.foldername(name))[1] IN (
      SELECT id::text FROM agencies WHERE owner_id = auth.uid()
      UNION
      SELECT agency_id::text FROM brokers WHERE user_id = auth.uid()
    )
  );

-- Roster uploads from brokers
CREATE TABLE IF NOT EXISTS roster_uploads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id uuid REFERENCES agencies(id) ON DELETE CASCADE NOT NULL,
  broker_id uuid REFERENCES brokers(id) NOT NULL,
  uploaded_by uuid REFERENCES auth.users(id) NOT NULL,
  carrier text NOT NULL,
  file_path text NOT NULL,
  row_count integer,
  matched_count integer,
  missing_count integer,
  new_count integer,
  status text DEFAULT 'processing'
    CHECK (status IN ('processing','complete','failed','needs_review')),
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE roster_uploads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "roster_principal_all" ON roster_uploads
  FOR ALL USING (is_principal(agency_id));
CREATE POLICY "roster_broker_own" ON roster_uploads
  FOR ALL USING (uploaded_by = auth.uid());

-- Individual roster members from uploaded file
CREATE TABLE IF NOT EXISTS roster_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  upload_id uuid REFERENCES roster_uploads(id) ON DELETE CASCADE NOT NULL,
  agency_id uuid REFERENCES agencies(id) ON DELETE CASCADE NOT NULL,
  carrier text NOT NULL,
  member_id text,
  full_name text,
  name_hash text NOT NULL,
  dob_hash text,
  effective_date date,
  plan_name text,
  plan_id text,
  status text,
  raw_row jsonb,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE roster_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "roster_members_principal" ON roster_members
  FOR ALL USING (is_principal(agency_id));

-- Switch alerts generated by diff engine
CREATE TABLE IF NOT EXISTS switch_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id uuid REFERENCES agencies(id) ON DELETE CASCADE NOT NULL,
  ghl_contact_id text NOT NULL,
  broker_id uuid REFERENCES brokers(id),
  upload_id uuid REFERENCES roster_uploads(id),
  alert_type text NOT NULL
    CHECK (alert_type IN (
      'missing_from_roster',
      'plan_change_detected',
      'new_enrollment',
      'status_change'
    )),
  previous_value text,
  new_value text,
  carrier text NOT NULL,
  priority text DEFAULT 'high'
    CHECK (priority IN ('critical','high','medium','low')),
  status text DEFAULT 'open'
    CHECK (status IN ('open','contacted','resolved','dismissed')),
  resolved_by uuid REFERENCES auth.users(id),
  resolved_at timestamp with time zone,
  ghl_workflow_triggered boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE switch_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "alerts_principal_all" ON switch_alerts
  FOR ALL USING (is_principal(agency_id));
CREATE POLICY "alerts_broker_own" ON switch_alerts
  FOR SELECT USING (
    broker_id IN (SELECT id FROM brokers WHERE user_id = auth.uid())
  );

-- Carrier email inbox for automatic roster parsing
CREATE TABLE IF NOT EXISTS carrier_email_forwards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id uuid REFERENCES agencies(id) ON DELETE CASCADE NOT NULL,
  broker_id uuid REFERENCES brokers(id),
  carrier text NOT NULL,
  forward_address text UNIQUE NOT NULL,
  active boolean DEFAULT true,
  last_received_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);
ALTER TABLE carrier_email_forwards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "email_forwards_principal" ON carrier_email_forwards
  FOR ALL USING (is_principal(agency_id));
